In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer

In [2]:
df = pd.read_csv("emoji_df_excel.csv")

In [3]:
df.head()

,emoji,name,group,sub_group,codepoints,labels
0,😀,grinning face,Smileys & Emotion,face-smiling,1F600,"face, grinning, smiling, joy, teeth, pleasure,..."
1,😃,grinning face with big eyes,Smileys & Emotion,face-smiling,1F603,"face, grinning, smiling, joy, teeth, big eyes,..."
2,😄,grinning face with smiling eyes,Smileys & Emotion,face-smiling,1F604,"face, grinning, smiling, joy, laughing, smilin..."
3,😁,beaming face with smiling eyes,Smileys & Emotion,face-smiling,1F601,"face, beaming, smiling, joy, laughing, smiling..."
4,😆,grinning squinting face,Smileys & Emotion,face-smiling,1F606,"face, grinning, squinting, joy, laughing, broa..."

In [4]:
df = df[:91]
df.head()

,emoji,name,group,sub_group,codepoints,labels
0,😀,grinning face,Smileys & Emotion,face-smiling,1F600,"face, grinning, smiling, joy, teeth, pleasure,..."
1,😃,grinning face with big eyes,Smileys & Emotion,face-smiling,1F603,"face, grinning, smiling, joy, teeth, big eyes,..."
2,😄,grinning face with smiling eyes,Smileys & Emotion,face-smiling,1F604,"face, grinning, smiling, joy, laughing, smilin..."
3,😁,beaming face with smiling eyes,Smileys & Emotion,face-smiling,1F601,"face, beaming, smiling, joy, laughing, smiling..."
4,😆,grinning squinting face,Smileys & Emotion,face-smiling,1F606,"face, grinning, squinting, joy, laughing, broa..."

## Turn the labels to one-hot encording

In [5]:
one_hot = df.labels.str.split('\s*,\s*', expand=True) \
   .stack() \
   .str.get_dummies() \
   .sum(level=0)
one_hot.head()

,$,><,Cheese,ROFL,X-shaped eyes,XD,abashed,admiration,adoration,adventure,...,winking,woozy,worried,wow,yawning,zany,zip it,zipper,zipper mouth,zzz
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df = df.drop(columns='labels').join(one_hot, how='outer')
df.head()

,emoji,name,group,sub_group,codepoints,$,><,Cheese,ROFL,X-shaped eyes,...,winking,woozy,worried,wow,yawning,zany,zip it,zipper,zipper mouth,zzz
0,😀,grinning face,Smileys & Emotion,face-smiling,1F600,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,😃,grinning face with big eyes,Smileys & Emotion,face-smiling,1F603,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,😄,grinning face with smiling eyes,Smileys & Emotion,face-smiling,1F604,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,😁,beaming face with smiling eyes,Smileys & Emotion,face-smiling,1F601,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,😆,grinning squinting face,Smileys & Emotion,face-smiling,1F606,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df.iloc[:5, np.r_[0, 5:len(df.columns)]]

,emoji,$,><,Cheese,ROFL,X-shaped eyes,XD,abashed,admiration,adoration,...,winking,woozy,worried,wow,yawning,zany,zip it,zipper,zipper mouth,zzz
0,😀,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,😃,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,😄,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,😁,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,😆,0,1,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0